remote_theme: "mmistakes/jekyll-theme-basically-basic"
title: LCI Fantasy Football
description: Overview of the league with seasonal stats and league history
logo: /assets/logo.png

twitter_username: TheFifthsWord
github_username:  regsmith
plugins:
  - jekyll-feed
  - jekyll-redirect-from

regsmith:
  name: Reg Smith
  twitter: TheFifthsWord
  picture: /assets/authors/regsmith.jpeg

whitelist:
  - jekyll-redirect-from

collections:
  season_archive:
    output: true
    permalink: /seasons/:name/

defaults:
  - scope:
      path: ""
      type: season_archive
    values:
      layout: season_archive

supabase:
  url: "https://achzrhabaqtucezkuycq.supabase.co"
  publishable_key: "sb_publishable_AdnPevt8vWg--DrnuLhxOA_DoRKiIw1"
  commissioner_email: "reg.smith89@gmail.com"

dues:
  default_season: 2026
